# Generated by Django 4.1.3 on 2022-12-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MVT18Daneri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='fecha',
            field=models.DateField(verbose_name='DD/MM/YYYY'),
        ),
    ]
